
# make sure we have the following import
from datetime import time as tm


users = ['Albert',
		 'Betty',
		 'Charles',
		 'David',
		 'Edmond',
		 'Fiona',
		 'George',
		 'Heidi',
		 'Ilia',
		 'Joanna',
		 'Klingon',
		 'Leona',
		 'Manitosa',
		 'Nobleton',
		 'Ottawa',
		 'Peterson Little',
		 'Questrade',
		 'Robbertelle',
		 'Samsung Electronics',
		 'To-be-or-not-to-be',
		 'UCLA-Campus',
		 'Valentino',
		 'Whatever-Waterloo',
		 'Xavier the Gifted School',
		 'Yellow Submarine',
		 'Zebra Zoo']
		 
meanTime = [tm(7,50),
			tm(8,33),
			tm(9,12),
			tm(10,15),
			tm(7,55),
			tm(8,10),
			tm(9,22),
			tm(10,34),
			tm(7,45),
			tm(8,45),
			tm(8,55),
			tm(9,2),
			tm(8,33),
			tm(8,32),
			tm(10,18),
			tm(8,44),
			tm(9,34),
			tm(8,55),
			tm(8,40),
			tm(9,54),
			tm(8,54),
			tm(9,28),
			tm(9,33),
			tm(10,2),
			tm(9,26),
			tm(8,56)]
			
print ('size of users =', len(users))
print ('size of meanTime =', len(meanTime))